#!/usr/bin/env node
// Bundles the sources in _js/ and _css/ into the files the pages load:
//   _js/site.js   -> assets/js/site.js    (home, archives, about)
//   _js/post.js   -> assets/js/post.js    (articles)
//   _css/site.css -> assets/css/site.css
//
// GitHub Pages only runs Jekyll, so the output is committed. CI runs this with
// --check and fails when it is out of date.
//
//   npm run build           rewrite the bundles
//   npm run check:bundle    fail if they differ from a fresh build

import { build } from 'esbuild';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');
const banner = 'Generated by scripts/build-assets.mjs. Do not edit.';

const common = {
  absWorkingDir: root,
  bundle: true,
  minify: true,
  legalComments: 'none',
  charset: 'utf8',
  write: false,
  logLevel: 'warning'
};

const results = await Promise.all([
  build({
    ...common,
    entryPoints: { site: '_js/site.js', post: '_js/post.js' },
    outdir: 'assets/js',
    format: 'iife',
    target: 'es2020',
    sourcemap: 'linked',
    banner: { js: `/* ${banner} Source: _js/ */` }
  }),
  build({
    ...common,
    entryPoints: { site: '_css/site.css' },
    outdir: 'assets/css',
    banner: { css: `/* ${banner} Source: _css/ */` }
  })
]);

const stale = [];
for (const file of results.flatMap((result) => result.outputFiles)) {
  const current = existsSync(file.path) ? readFileSync(file.path, 'utf8') : null;
  if (current === file.text) continue;
  stale.push(file.path.replace(`${root}/`, ''));
  if (!check) {
    mkdirSync(dirname(file.path), { recursive: true });
    writeFileSync(file.path, file.text);
  }
}

if (check && stale.length) {
  console.error(`Out of date, run "npm run build": ${stale.join(', ')}`);
  process.exit(1);
}
console.log(stale.length && !check ? `Wrote ${stale.join(', ')}` : 'Bundles up to date');
